services:
  mc:
    image: itzg/minecraft-server:java21
    container_name: arcana-dev
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21.11"
      MEMORY: 2G
      ONLINE_MODE: "TRUE"
      DIFFICULTY: normal
      VIEW_DISTANCE: 6
      SIMULATION_DISTANCE: 4
      MODRINTH_PROJECTS: luckperms,griefprevention
      OPS: vegabernh
    volumes:
      - ./data:/data
